[features]
seeds = true
skip-lint = false

[programs.devnet]
ert_stablecoin = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"  # Example program ID; generate yours

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
pyth-sdk-solana = "0.8.0"  # For oracle price feeds
light-protocol = "1.0"     # For zk-SNARKs (privacy proofs)
anchor-spl = "0.29.0"      # Token standards
