[features]
seeds = false
skip-lint = false

[programs.localnet]
ert_stablecoin = "YourProgramIDHere"  # Replace with actual ID after build

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"  # Start with devnet for testing
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
